models:
  llm:
    model: ${DOCKER_RUNNER_MODEL:-ai/gpt-oss:latest}
    context_size: 4000

services:
  mysql:
    image: mysql:8.0
    container_name: sakila-mysql
    environment:
      MYSQL_ROOT_PASSWORD: sakila_password
      MYSQL_DATABASE: sakila_es
    ports:
      - "3307:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: .
    container_name: front-end
    ports:
      - "8080:3000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=sakila_password
      - DB_NAME=sakila_es

  python-backend:
    build: ./python-backend
    container_name: sql-agent-python
    ports:
      - "5000:5000"
    environment:
      - LLM_PROVIDER=${LLM_PROVIDER:-openai}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4}
      - DOCKER_RUNNER_BASE_URL=http://host.docker.internal:12434/engines/llama.cpp/v1/
      - DOCKER_RUNNER_MODEL=${DOCKER_RUNNER_MODEL:-ai/gpt-oss:latest}
      - PORT=5000
      - DEBUG=true
    models:
      - llm
    profiles:
      - with-llm
      - full

